# Generated by Django 6.0.3 on 2026-04-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
