# Generated by Django 6.0.3 on 2026-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0004_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
